ARG TENSORFLOW_VERSION=2.17.0
ARG CUDA
FROM quay.io/jupyter/tensorflow-notebook:${CUDA}tensorflow-${TENSORFLOW_VERSION}

LABEL org.opencontainers.image.description="Combines the Docker Stacks tensorflow-notebook and pytorch-notebook containers plus jupytext and custom package additions."

# must redefine as initial definition has gone out of scope
ARG TENSORFLOW_VERSION=2.17.0
ARG CUDA

LABEL "org.opencontainers.image.authors"="Hilmar Lapp <hilmar.lapp@duke.edu>"
LABEL "org.opencontainers.image.description"="Jupyter Lab (without GPU support) for Biostat courses"

RUN apt-get update && apt-get install --yes \
    libcurl4-openssl-dev

# We follow the standard recommended recipe for custom builds off of Jupyter Docker Stacks
RUN mamba install --yes \
    'jupytext' && \
    mamba clean --all -f -y && \
    fix-permissions "${CONDA_DIR}" && \
    fix-permissions "/home/${NB_USER}"

# Uninstall tensorflow-cpu, which could have been installed on the x86_64
# platform for CPU-only, and in that case reinstall as plain tensorflow.
#
# Otherwise we end up with a redundant installation because some dependency
# chains (such as keras-nlp->tensorflow-text->tensorflow) will result in a
# tensorflow requirement which doesn't resolve to tensorflow-cpu.
RUN [[ $(uname -m) = x86_64 && -z ${CUDA} ]] &&  \
    pip uninstall -y "tensorflow-cpu" && \
    pip install --no-cache-dir tensorflow==${TENSORFLOW_VERSION} && \
    fix-permissions "${CONDA_DIR}" && \
    fix-permissions "/home/${NB_USER}" || \
    true

# Separate installation of PyTorch to use CPU-only version according to instructions
# See https://pytorch.org/get-started/locally/
RUN [[ -n ${CUDA} ]] && \
    EXTRA_INDEX="--extra-index-url=https://pypi.nvidia.com" CUDA_WHL_SUFFIX="cu121" || \
    EXTRA_INDEX="" CUDA_WHL_SUFFIX="cpu" && \
    pip install --no-cache-dir $EXTRA_INDEX --index-url "https://download.pytorch.org/whl/${CUDA_WHL_SUFFIX}" \
    torch \
    torchvision \
    torchaudio && \
    fix-permissions "${CONDA_DIR}" && \
    fix-permissions "/home/${NB_USER}"

# Additional packages we may need
COPY requirements.txt /tmp/addon-requirements.txt
RUN pip install --no-cache-dir \
    -r /tmp/addon-requirements.txt && \
    fix-permissions "${CONDA_DIR}" && \
    fix-permissions "/home/${NB_USER}"

# Base directory for ontologies cached by OAK
ENV PYSTOW_HOME=$HOME/.cache/oak/
