name: Create and publish CUDA-enabled images

on:
  push:
    branches: main
    paths-ignore:
      - 'LICENSE'
      - 'README.md'
      - '.github/workflows/build-deploy.yml'
      - '.github/workflows/build-deploy-keras2.yml'
      - 'requirements.tf-2.15.0.txt'
  release:
    types: [published]

env:
  REGISTRY: ghcr.io
  IMAGE_NAME: ${{ github.repository }}
  TF_VERSION: 2.17.0

jobs:
  build-and-push-pyimage:
    permissions:
      contents: read
      packages: write

    uses: ./.github/workflows/build-deploy-py.yml
    with:
      tf_version: 2.17.0
      basedigest: "@sha256:cb1cac983d469ddd8702c382b01a6c02bbb9c9fda1765caf269b38f2d228f9d8"
      cuda: true
      tag_latest: false
      multiplatform: false
      image_description: Combines the Docker Stacks tensorflow-notebook and pytorch-notebook containers with CUDA enabled plus jupytext and custom package additions.

  build-and-push-image-withR:
    needs: build-and-push-pyimage
    permissions:
      contents: read
      packages: write

    uses: ./.github/workflows/build-deploy-withR.yml
    with:
      tf_version: 2.17.0
      cuda: true
      tag_latest: false
      multiplatform: false
      image_description: Combines the Docker Stacks tensorflow-notebook, pytorch-notebook, and r-notebook containers with CUDA enabled plus jupytext and custom package additions.

